### ISSUE TITLE
三方书源测试搜索程序一直闪退

### ISSUE THREAD

**Issue by 755048652** [fengyuecanzhu/FYReader#19]
自己用代码编译的app不能用第三方书源，导入之后测试搜索时程序闪退。

**Comment by fengyuecanzhu** [comment]
经测试发现是编译后无法识别出[类JsExtensions.java](https://github.com/fengyuecanzhu/FYReader/blob/master/app/src/main/java/xyz/fycz/myreader/util/help/JsExtensions.java)，暂时不清楚是什么问题（因为一直是Github Actions自动打包），建议本地编译前修改下[此类](https://github.com/fengyuecanzhu/FYReader/blob/master/app/src/main/java/xyz/fycz/myreader/util/help/JsExtensions.java)即可解决此问题

**Comment by fengyuecanzhu** [comment]
> 经测试发现是编译后无法识别出[类JsExtensions.java](https://github.com/fengyuecanzhu/FYReader/blob/master/app/src/main/java/xyz/fycz/myreader/util/help/JsExtensions.java)，暂时不清楚是什么问题（因为一直是Github Actions自动打包），建议本地编译前修改下[此类](https://github.com/fengyuecanzhu/FYReader/blob/master/app/src/main/java/xyz/fycz/myreader/util/help/JsExtensions.java)即可解决此问题

在不同平台下编译测试发现，只有Windows出现此问题(可能是Windows文件名没有大小写区分)，在Linux及Mac系统均未出现问题，建议在Linux或Mac环境下编译，Windows下扔可使用上述方法进行编译

**Comment by fengyuecanzhu** [comment]
新版本已修复此问题
